### ISSUE TITLE
parser.py --test : ValueError: could not broadcast input array from shape (63) into shape (64)

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [chantera/biaffineparser#4]
**Hi , When I run the test , the following error occurs：**
file:  <class 'str'>
model_file:  <class 'chainer_model.DeepBiaffine'>
2019-01-29 11:03:57.087 CST     bfc81b  [trace] Orthogonal pretrainer loss: 4.45e-29
2019-01-29 11:03:58.607 CST     bfc81b  [trace] Orthogonal pretrainer loss: 4.24e-29
2019-01-29 11:03:58.623 CST     bfc81b  [error] Exception occurred during execution:
Traceback (most recent call last):
  File "/home/lxiao/workspace/BiaffineParser/src/teras/teras/app/__init__.py", line 58, in run
    self._process()
  File "/home/lxiao/workspace/BiaffineParser/src/teras/teras/app/__init__.py", line 102, in _process
    self._command(**kwargs)
  File "parser.py", line 221, in test
    _load_test_model(model, model_file, device_id=gpu)
  File "parser.py", line 180, in _load_test_model
    chainer.serializers.load_npz(file, model)
  File "/home/lxiao/anaconda3/lib/python3.6/site-packages/chainer/serializers/npz.py", line 140, in load_npz
    d.load(obj)
  File "/home/lxiao/anaconda3/lib/python3.6/site-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/home/lxiao/anaconda3/lib/python3.6/site-packages/chainer/link.py", line 795, in serialize
    d[name].serialize(serializer[name])
  File "/home/lxiao/anaconda3/lib/python3.6/site-packages/chainer/link.py", line 551, in serialize
    data = serializer(name, param.data)
  File "/home/lxiao/anaconda3/lib/python3.6/site-packages/chainer/serializers/npz.py", line 113, in __call__
    numpy.copyto(value, dataset)
**ValueError: could not broadcast input array from shape (63) into shape (64)**
2019-01-29 11:03:58.624 CST     bfc81b  [info]  LOG End with ACCESSID=[bfc81b] UNIQUEID=[UNIQID] ACCESSTIME=[2019                                                    -01-29 11:03:16.919340 CST] PROCESSTIME=[41.704970000]

PS: my test data as follows:
```
1	只有	只有	_	_	_	7	obj	_	_
2	是	是	_	_	_	2	obj	_	_
3	签署	签署	_	_	_	7	obj	_	_
4	协定	协定	_	_	_	3	obj	_	_
5	两国	两国	_	_	_	4	obj	_	_
6	的	的	_	_	_	3	obj	_	_
7	居民	居民	_	_	_	10	obj	_	_
8	才	才	_	_	_	10	obj	_	_
9	会	会	_	_	_	10	obj	_	_
10	使用	使用	_	_	_	0	root	_	_
11	该	该	_	_	_	12	obj	_	_
12	协定	协定	_	_	_	14	obj	_	_
13	的	的	_	_	_	12	obj	_	_
14	条款	条款	_	_	_	10	obj	_	_
15	。	。	_	_	_	10	obj	_	_

```

**Comment by chantera** [comment]
I guess you use different sets of dependency relations.
If you train the model for 63 deprels but use an unseen deprel in testing,
the deprel classifier is initialized for 64 deprels but the trained model has weights for 63 deprels.
Please make sure len(loader.label_map) in training is equal to len(loader.label_map) in testing.
