### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (37,100) (37,300)

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [chantera/biaffineparser#5]
2019-02-18 20:48:24.230 CST     e2989e  [info]  saving the context to model/20190218-e2989e.context ...
  0%|                                                                                                                      | 0/3997 [00:00<?, ?it/s]2019-02-18 20:48:24.748 CST     e2989e  [error] Exception occurred during execution:
Traceback (most recent call last):
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/teras/teras/app/app.py", line 60, in run
    self._process()
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/teras/teras/app/app.py", line 104, in _process
    self._command(**kwargs)
  File "src/main.py", line 73, in train
    trainer.fit(train_dataset, test_dataset, n_epoch, batch_size)
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/teras/teras/training/trainer.py", line 107, in fit
    main_loop()
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/teras/teras/training/trainer.py", line 98, in main_loop
    self._process(forward, train_dataset, lossfun, convert, batch_size, epoch_logs)
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/teras/teras/training/trainer.py", line 145, in _process
    ys = forward(*xs)
  File "/home/liuxiao/miniconda3/lib/python3.6/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/models.py", line 122, in forward
    self._hs = self.encoder(words, pretrained_words, postags)
  File "/home/liuxiao/miniconda3/lib/python3.6/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/models.py", line 264, in forward
    rs = self._concat_embeds(self.embeds(*xs))
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/models.py", line 274, in _concat_embeds
    rs_words = [rs_word_seq + rs_pre_seq for rs_word_seq, rs_pre_seq in zip(rs_words, rs_words_pretrained)]
  File "/home/liuxiao/workspace/dependency-parser/biaffineparser/src/models.py", line 274, in <listcomp>
    rs_words = [rs_word_seq + rs_pre_seq for rs_word_seq, rs_pre_seq in zip(rs_words, rs_words_pretrained)]
  File "/home/liuxiao/miniconda3/lib/python3.6/site-packages/chainer/functions/math/basic_math.py", line 229, in add
    return Add().apply((lhs, rhs))[0]
  File "/home/liuxiao/miniconda3/lib/python3.6/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home/liuxiao/miniconda3/lib/python3.6/site-packages/chainer/functions/math/basic_math.py", line 156, in forward
    y = utils.force_array(x[0] + x[1])
ValueError: operands could not be broadcast together with shapes (37,100) (37,300)
**When using a pre-trained word vector file with a dimension of 300, the following error is exposed. Also modified to word_embed_size=300 in dataset.py**
**Would you share the word vector file you used in your code? Thank you so much!**

**Comment by chantera** [comment]
The program creates a cache of a dataset for a set of the latest git commit hash, a train_file path, a test_file path, and embed_file path.
So if you change `word_embed_size` after creating the cache, you have to recreate a cache with the command line argument `--refresh`.

**Comment by xiaoxiaoAurora** [comment]
> The program creates a cache of a dataset for a set of the latest git commit hash, a train_file path, a test_file path, and embed_file path.
> So if you change `word_embed_size` after creating the cache, you have to recreate a cache with the command line argument `--refresh`.

OK! thank you very much!
